M48
; DRILL file {KiCad 7.0.6} date Mon Aug  7 22:53:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T22:53:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.000
%
G90
G05
T1
X112.7Y-91.35
X151.45Y-52.4
X151.45Y-130.1
X190.4Y-91.35
T0
M30
